apiVersion: v1
kind: Service
metadata:
  name: cropguard-ai-svc
spec:
  type: NodePort
  selector: { app: cropguard-ai }
  ports: [{ port: 80, targetPort: 5000 }]
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: cropguard-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cropguard-cert
spec:
  domains:
    - "136.68.254.106.sslip.io"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cropguard-ingress
  annotations:
    networking.gke.io/managed-certificates: cropguard-cert
    networking.gke.io/v1beta1.FrontendConfig: cropguard-frontend-config
    kubernetes.io/ingress.global-static-ip-name: cropguard-ip
spec:
  defaultBackend:
    service: { name: cropguard-ai-svc, port: { number: 80 } }
